name: Auto Update Chapter Every Day

on:
    schedule:
        # Runs at 13:00 UTC (20:00 Vietnam time)
        - cron: '0 13 * * *'

jobs:
    ping:
        runs-on: ubuntu-latest
        env:
            URL: ${{ secrets.RENDER_SERVICE_URL }}/update-all-story
            METHOD: POST
        steps:
            - name: Auto update chapter every day
              uses: sisodiya2421/pinger@v3
