name: Auto Update Chapter Every Day

on:
    schedule:
        # Runs at 13:00 UTC (20:00 Vietnam time)
        - cron: '*/60 * * * *'

jobs:
    ping:
        runs-on: ubuntu-latest
        steps: 
            - name: Update chapter
              run: |
                  curl -X POST \
                   -H "Content-Type: application/json" \
                   ${{ secrets.RENDER_SERVICE_URL }}/update-all-story
