name: Keep Render Service Alive

on:
    schedule:
        - cron: '*/10 * * * *'

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Ping the render service
              run: curl -s "${{ secrets.RENDER_SERVICE_URL }}" > /dev/null
