name: Keep Render Service Alive

on:
    schedule:
        - cron: '*/10 * * * *'

jobs:
    ping:
        runs-on: ubuntu-latest
        env:
            URL: ${{ secrets.RENDER_SERVICE_URL }}
            METHOD: GET
        steps:
            - name: Ping Render service to keep it alive
              uses: sisodiya2421/pinger@v3
